name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    - 
      name: Build the Docker image
      run: docker build -t cdrachel/clientimg -f Dockerfile .
    -
      name: Generate Deployment Package
      run: zip -r deploy.zip *
    -
      name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time
      
    - 
      name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'
 
    -  name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"
          
    - name: Upload package to S3 bucket
      run: aws s3 cp deploy.zip s3://my-was-deploy-cdbuckets3-server/
      
    - name: Create new ElasticBeanstalk Application Version
      run: |
          aws elasticbeanstalk create-application-version \
          --application-name serverside \
          --source-bundle S3Bucket="my-was-deploy-cdbuckets3-server",S3Key="deploy.zip" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"
          
    - name: Deploy new ElasticBeanstalk Application Version
      run: aws elasticbeanstalk update-environment --environment-name serverenv --version-label "ver-${{ github.sha }}"
